// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using contasoft_api.Data;

#nullable disable

namespace contasoft_api.Migrations
{
    [DbContext(typeof(ContaSoftDbContext))]
    [Migration("20240110202451_dev01")]
    partial class dev01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("contasoft_api.Models.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("contasoft_api.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("RNC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("contasoft_api.Models.Invoice606", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FechaComprobante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaPago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FormaDePago")
                        .HasColumnType("int");

                    b.Property<decimal?>("IRSPercibidoEnCompras")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ITBISFacturado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ITBISLlevadoAlCosto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ITBISPersividoEnCompras")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ITBISPorAdelantar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ITBISRetenido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ITBISSujetoaProporcionalidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ImpuestoSelectivoAlConsumo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MontoFacturadoEnBienes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MontoFacturadoEnServicio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MontoPropinaLegal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MontoRetencionRenta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroComprobanteFiscal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroComprobanteFiscalModificado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("O606Id")
                        .HasColumnType("int");

                    b.Property<string>("OtrosImpuestosTasa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RNCCédulaPasaporte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoBienesYServiciosComprados")
                        .HasColumnType("int");

                    b.Property<int>("TipoID")
                        .HasColumnType("int");

                    b.Property<int?>("TipoRetencionEnISR")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalMontoFacturado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("O606Id");

                    b.ToTable("Invoice606");
                });

            modelBuilder.Entity("contasoft_api.Models.Invoice607", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BonosOCertificadosRegalo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cheque_Transferencia_Depósito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Efectivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaComprobante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaRetención")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISRPercibido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ITBISFacturado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ITBISPercibido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ITBISRetenidoporTerceros")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImpuestoSelectivoalConsumo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MontoFacturado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MontoPropinaLegal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroComprobanteFiscal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroComprobanteFiscalModificado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("O607Id")
                        .HasColumnType("int");

                    b.Property<string>("OtrasFormasVentas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtrosImpuestos_Tasas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Permuta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RNCCédulaPasaporte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RetenciónRentaporTerceros")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TarjetaDébito_Crédito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoIdentificación")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoIngreso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VentaACrédito")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("O607Id");

                    b.ToTable("Invoice607");
                });

            modelBuilder.Entity("contasoft_api.Models.O606", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearMonth")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("O606");
                });

            modelBuilder.Entity("contasoft_api.Models.O607", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearMonth")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("O607");
                });

            modelBuilder.Entity("contasoft_api.Models.Plan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("AccountsNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("period")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Plan");
                });

            modelBuilder.Entity("contasoft_api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Cellphone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("contasoft_api.Models.UserCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCompany");
                });

            modelBuilder.Entity("contasoft_api.Models.Client", b =>
                {
                    b.HasOne("contasoft_api.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("contasoft_api.Models.Invoice606", b =>
                {
                    b.HasOne("contasoft_api.Models.O606", "O606")
                        .WithMany()
                        .HasForeignKey("O606Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("O606");
                });

            modelBuilder.Entity("contasoft_api.Models.Invoice607", b =>
                {
                    b.HasOne("contasoft_api.Models.O607", "O607")
                        .WithMany()
                        .HasForeignKey("O607Id");

                    b.Navigation("O607");
                });

            modelBuilder.Entity("contasoft_api.Models.O606", b =>
                {
                    b.HasOne("contasoft_api.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("contasoft_api.Models.O607", b =>
                {
                    b.HasOne("contasoft_api.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("contasoft_api.Models.User", b =>
                {
                    b.HasOne("contasoft_api.Models.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("contasoft_api.Models.UserCompany", b =>
                {
                    b.HasOne("contasoft_api.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("contasoft_api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
